name       : openastro-data
version    : 1.8
release    : 2
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org-data/openastro.org-data_1.8.orig.tar.gz : 4109e3ee57f93bfa73b4949aeba4d0c38b0610ed848e3bf55be572fa5b491c38
license    : GPL-3.0-or-later
component  : desktop
summary    : Data for OpenAstro
description: |
    Data for OpenAstro
setup      : |
    %python3_setup
install    : |
    %python3_install
