name       : openastro-data
version    : 1.6
release    : 1
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org-data/openastro.org-data_1.6.orig.tar.gz : 1ea8a80ebb6077f2b5f4abafe532037a2bf6ff060afba5419cf1f5aaa0890370
license    : GPL-3.0
component  : desktop
summary    : Data for OpenAstro
description: |
    Data for OpenAstro
builddeps  :
    - python-setuptools
setup      : |
    %python_setup
install    : |
    %python_install
