name       : openastro-data
version    : '.9
release    : 3
source     :
    - http://ppa.launchpad.net/pellesimon/ubuntu/pool/main/o/openastro.org-data/openastro.org-data_1.9.orig.tar.gz : 98887b77f924bef2586e53f001a5972c3903cbc0bdb50adb3af97fe8a3fed91e
license    : GPL-3.0-or-later
component  : desktop
summary    : Data for OpenAstro
description: |
    Data for OpenAstro
setup      : |
    %python3_setup
install    : |
    %python3_install
